In [29]:
import numpy as np
mu2=np.linspace(0.01,1, 20)
num_sample =3 
#pc 
mu2=mu2[0:num_sample]
num_time=3
time= np.linspace(0,num_time,num_time)


In [30]:
params= np.zeros((len(time),2) )
params[:,0]= np.ones((len(time), 1)).reshape(-1,)
params[:,0]*=np.round(mu2[0],4)
params[:,1] = time

In [33]:
for i in range(1, len(mu2)):
    tmp_ = np.zeros((len(time),2))
    tmp_[:,0]= np.ones((len(time), 1)).reshape(-1,)
    tmp_[:,0]*=np.round(mu2[i],4) # tmp_[:,0]= tmp_[:,0]*mu2[i]    
    tmp_[:,1] = time
    params = np.vstack((params,tmp_))
    
#print(params)
print(params.shape)

(174, 2)


In [49]:
import os
import numpy as np
snapshot = np.loadtxt('U1_1.csv',delimiter=",")


(0, 0)


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 0 and the array at index 1 has size 3

In [61]:
#import os
#files=os.listdir(os.getcwd())
#print(files)
snapshot = np.loadtxt('U1_1.csv',delimiter=",")
print(snapshot.shape)

for i in range(1, num_sample):
    #testing
    # j=1
    # tmp_s= np.loadtxt("U1_{}.csv".format(j),delimiter=",")
    # real code
    tmp_s= np.loadtxt("U1_{}.csv".format(i+1),delimiter=",")
    snapshot= np.hstack((snapshot, tmp_s))
    print(snapshot.shape)
    print(tmp_s)
    del tmp_s


(4662, 3)
(4662, 6)
[[0.         0.00054395 0.00109173]
 [0.         0.00302823 0.00601174]
 [0.         0.00303472 0.00602887]
 ...
 [0.         0.00040972 0.00081521]
 [0.         0.0004544  0.00090684]
 [0.         0.00050094 0.00100304]]


OSError: U1_2.csv not found.

In [48]:
print(snapshot)

[[0.         0.00054395 0.00109173]
 [0.         0.00302823 0.00601174]
 [0.         0.00303472 0.00602887]
 ...
 [0.         0.00040972 0.00081521]
 [0.         0.0004544  0.00090684]
 [0.         0.00050094 0.00100304]]


In [62]:
np.savetxt('SnapshotMatrix.csv',snapshot, delimiter=",")
np.savetxt('SnapshotMatrix.npy',snapshot, delimiter=",")
np.savetxt('params.csv',params, delimiter=",")
np.savetxt('params.npy',params, delimiter=",")


In [87]:
import ezyrb
from ezyrb import POD, GPR, RBF, Database
from ezyrb import ReducedOrderModel as ROM
pod=POD('svd')
# RBF: input (parame,snapshot) 
# we choose the RBF interpolation among the parameters
rbf = RBF(kernel='multiquadric', smooth=0.65) #smooth is ur r.
#rbf = RBF(kernel='gaussian', smooth=0.65) #smooth is ur r.
# we build a database
mu2=np.linspace(0.01,1, 20)
num_sample =3 
#pc 
mu2=mu2[0:num_sample]
num_time=3
time= np.linspace(0,num_time,num_time)
params= np.zeros((len(time),2) )
params[:,0]= np.ones((len(time), 1)).reshape(-1,)
params[:,0]*=np.round(mu2[0],4)
params[:,1] = time
snapshot = np.loadtxt('U1_1.csv',delimiter=",")
print(len(params))
print(len(snapshot.T))
db = Database(params, snapshot.T)
# we construct the class and fit 
rom = ROM(db, pod, rbf).fit()
num_modes=rom.reduction._modes.shape[1]
for i in  range(0, num_modes):
    #print(rom.reduction._modes[:,i])
    np.savetxt("POD_{}.csv".format(i),rom.reduction._modes[:,i])
print(rom.reduction._singular_values)
np.savetxt("sigmas_.csv",rom.reduction._singular_values)
error= rom.loo_error()
print(error)

3
3
[0.19003655 0.00141766 0.        ]
[0.2700076  0.00900265 0.02469067]
